### ISSUE TITLE
doctrine-module dependency is forced to 0.8.* version

### ISSUE THREAD

**Issue by thomasvargiu** [API-Skeletons/zf-oauth2-doctrine#57] opened 2016-02-23 14:38 UTC
Setting `doctrine-module` requiring version `^0.8`, as it's a pre-1.0 release, means `>=0.8.0 <0.9.0`.
There is a problem with 0.9.*? Or just a mistake?

**Comment by TomHAnderson** [comment] 2016-02-23 16:54
The problem is DoctrineModule does not support ZF2 > 2.4.  I've been trying to get this corrected for over a month.  Comments on this thread are appreciated:

https://github.com/doctrine/DoctrineModule/issues/546

**Comment by TomHAnderson** [comment] 2016-05-19 18:11
Correction; the ZF2 > 2.4 issue is not at issue here.

**Comment by TomHAnderson** [comment] 2016-05-19 18:12
Fixed with https://github.com/API-Skeletons/zf-oauth2-doctrine/commit/fa40539f5a25f3c82b1a397f47bbdc61319c00d6

**Closed by TomHAnderson** 2016-05-19 18:12 UTC

**Comment by thomasvargiu** [comment] 2016-05-19 23:42
Should be better to use `~0.8 || ^1.0`

**Comment by thomasvargiu** [comment] 2016-05-25 17:06
@TomHAnderson is it really resolved? Is it possible to tag the master?
